#!/usr/bin/env bash
# Puts a `dbt` wrapper in .venv/bin so the dbt Power User extension finds the
# mise-pinned dbt Cloud CLI. See "VS Code / dbt Power User" in the README.
set -euo pipefail

cd "$(dirname "$0")/.."

cat > .venv/bin/dbt <<'EOF'
#!/usr/bin/env bash
# Generated by `mise run setup` — see README (VS Code / dbt Power User).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MISE="${MISE_BIN:-$HOME/.local/bin/mise}"
exec "$("$MISE" --cd "$REPO_ROOT" which dbt)" "$@"
EOF

chmod +x .venv/bin/dbt
echo "installed .venv/bin/dbt wrapper"
